### ISSUE TITLE
请问一下readme中提到的毕业论文在哪里可以下载呢，能不能提供相应的链接啊，杨明豪等人的复合式封包溯源的论文能否提供一个下载链接呢，谢谢了

### ISSUE THREAD

**Issue by jerrysj** [ultraman21/NS-3-traceback#1]

**Comment by ultraman21** [comment]
请问你是要做什么呢？

**Comment by jerrysj** [comment]
您好，我现在也是在做IP地址的溯源，github上只看到您开源了代码，希望可以结合代码和论文一起来学习，，我现在用了好几个NS-3版本都没能代码编译成功，不知道是否方便添加一下你的qq或者其他联系方式呢，我的qq是1657245052，非常感谢！！！

**Comment by jerrysj** [comment]
您好，这两天都在编译您的代码，都忘记了上来看看，希望可以添加一下qq，向您请教一点问题，不会频繁打扰您的。

**Comment by jerrysj** [comment]
还想请问一下，这个代码用的是哪个版本的NS-3呢，谢谢了

**Comment by ultraman21** [comment]
加了你Q，咋一直不通过呢？

**Comment by ultraman21** [comment]
杨明豪的论文是《High accuracy and low storage hybrid IP traceback》
知网链接http://d.scholar.cnki.net/detail/refdetail?tablename=SPIETEMP_U&filename=SPIE14120200092645
